Add missing fetcher_keystone options
We've seen workers of cloudkitty-processor continuously crash with
the following traceback logged in syslog

Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/cotyledon/_utils.py", line 63, in _bootstrap_process
    target(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cotyledon/_service.py", line 161, in create_and_wait
    sw = cls(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cotyledon/_service.py", line 175, in __init__
    self.service = config.service(worker_id, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cloudkitty/orchestrator.py", line 552, in __init__
    self.fetcher = driver.DriverManager(
  File "/usr/lib/python3.9/site-packages/stevedore/driver.py", line 54, in __init__
    super(DriverManager, self).__init__(
  File "/usr/lib/python3.9/site-packages/stevedore/named.py", line 78, in __init__
    extensions = self._load_plugins(invoke_on_load,
  File "/usr/lib/python3.9/site-packages/stevedore/extension.py", line 218, in _load_plugins
    self._on_load_failure_callback(self, ep, err)
  File "/usr/lib/python3.9/site-packages/stevedore/extension.py", line 206, in _load_plugins
    ext = self._load_one_plugin(ep,
  File "/usr/lib/python3.9/site-packages/stevedore/named.py", line 156, in _load_one_plugin
    return super(NamedExtensionManager, self)._load_one_plugin(
  File "/usr/lib/python3.9/site-packages/stevedore/extension.py", line 242, in _load_one_plugin
    obj = plugin(*invoke_args, **invoke_kwds)
  File "/usr/lib/python3.9/site-packages/cloudkitty/fetcher/keystone.py", line 71, in __init__
    auth_url=self.auth.auth_url)
AttributeError: 'NoneType' object has no attribute 'auth_url'

This adds the fetcher_keystone options to avoid that error.

Change-Id: I27530c279afd21f8b32ee6aa44ec194ac019887c